Fix one remaining case of direct reference to regexec
This breaks on some MinGW variants with:
recorder.c: In function "recorder_trace_set":
recorder.c:2320:29: warning: implicit declaration of function "regexec" [-Wimplicit-function-declaration]
                         if (regexec(&re, rec->name, 1, &rm, 0) == 0 &&
                             ^~~~~~~
recorder.c:2320:38: error: "re" undeclared (first use in this function)
                         if (regexec(&re, rec->name, 1, &rm, 0) == 0 &&
                                      ^~
recorder.c:2320:38: note: each undeclared identifier is reported only once for each function it appears in
recorder.c:2320:57: error: "rm" undeclared (first use in this function)
                         if (regexec(&re, rec->name, 1, &rm, 0) == 0 &&
                                                         ^~
recorder.c:2150:21: warning: unused variable "error" [-Wunused-variable]
     static char     error[128];
                     ^~~~~
At top level:
recorder.c:2150:21: warning: "error" defined but not used [-Wunused-variable]
recorder.c:952:13: warning: "recorder_shans_file_extend" defined but not used [-Wunused-function]
 static bool recorder_shans_file_extend(int fd, off_t new_size)